name: Compile PaDEL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  libPaDEL:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: |
        cd libPaDEL
        ant

  libPaDEL-Jobs:
    runs-on: ubuntu-latest
    needs: libPaDEL

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: |
        cd libPaDEL-Jobs
        ant

  libPaDEL-Descriptor:
    runs-on: ubuntu-latest
    needs: libPaDEL-Jobs

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: |
        cd libPaDEL-Descriptor
        ant

  PaDEL-Descriptor:
    runs-on: ubuntu-latest
    needs: libPaDEL-Descriptor

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: |
        ant
